name: mcache
description: Tools for caching values in memory. Supports setting the expiration of values.
version: 1.0.2
homepage: https://github.com/GlebBatykov/cache

environment:
  sdk: ">=2.17.5 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
